# Generated by Django 3.0.8 on 2020-07-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=50)),
                ('query_subject', models.CharField(max_length=50)),
                ('query_text', models.CharField(max_length=200)),
            ],
        ),
    ]
